P8105 Homework 2
================
Madison Goldrich - mpg2166

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.3     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.0
    ## ✔ ggplot2   3.4.3     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

## Problem 1

First, clean the data in pols-month.csv

``` r
pols_month_df =
  read_csv("data/pols-month.csv") |> 
  separate(
    mon,
    sep = "-",
    into = c("year", "month", "day")
  ) |> 
  mutate(
    month = case_match(
      month,
      "01" ~ "Jan",
      "02" ~ "Feb",
      "03" ~ "Mar",
      "04" ~ "Apr",
      "05" ~ "May",
      "06" ~ "Jun",
      "07" ~ "Jul",
      "08" ~ "Aug",
      "09" ~ "Sep",
      "10" ~ "Oct",
      "11" ~ "Nov",
      "12" ~ "Dec"
    )
  ) |> 
  mutate(
    president = case_match(
      prez_gop,
      0 ~ "dem",
      1 ~ "gop"
     )
    ) |> 
  select(-day, -prez_gop, -prez_dem)
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Second, clean the data in snp.csv

``` r
snp_df =
  read_csv("data/snp.csv") |> 
    separate(
    date,
    sep = "/",
    into = c("month", "day", "year")
  ) |> 
  mutate(
    year = as.numeric(year),
    month = as.numeric(month)
  ) |> 
  mutate(
    year = case_when(
      year <=15 ~ year + 2000,
      year > 15 ~ year + 1900
    )
  ) |> 
  select(year, month, close) |> 
  arrange(year, month) |> 
  mutate(
    month = case_match(
      month,
      1  ~ "Jan",
      2  ~ "Feb",
      3  ~ "Mar",
      4  ~ "Apr",
      5  ~ "May",
      6  ~ "Jun",
      7  ~ "Jul",
      8  ~ "Aug",
      9  ~ "Sep",
      10 ~ "Oct",
      11 ~ "Nov",
      12 ~ "Dec"
    )
  ) |> 
  mutate(
    year = as.character(year)
  )
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Third, tidy the unemployment data so that it can be merged with the
previous datasets.

``` r
unemployment_df =
  read.csv("data/unemployment.csv") |> 
  pivot_longer(
    Jan:Dec,
    names_to = "month",
    values_to = "unemployment"
  ) |> 
  janitor::clean_names() |> 
  mutate(
    year = as.character(year)
  )
```

Join the datasets

``` r
pols_snp_df =
  left_join(pols_month_df, snp_df)
```

    ## Joining with `by = join_by(year, month)`

``` r
five_thirty_eight_df =
  left_join(pols_snp_df, unemployment_df)
```

    ## Joining with `by = join_by(year, month)`

The pols-month dataset initially contained 9 variables related to the
number of national politicians (i.e., president, senators,
representatives, etc.) who were democratic or republican at any given
time. The snp dataset contained the closing values of the S&P stock
index (`close`) on the associated date. Unemployment dataset contained
the percentage of unemployment (`unemployment`) in the associated
month/year. The resulting merged dataset is 822 rows by 11 columns.
Years in which data was collected range from 1947 to 2015.

## Problem 2

``` r
library(readxl)
```

Read and clean the Mr. Trash Wheel sheet.

``` r
mr_trash_wheel_df =
  read_excel(
    "data/202207 Trash Wheel Collection Data.xlsx",
    sheet = "Mr. Trash Wheel",
    range = "A2:N549") |> 
  janitor::clean_names() |> 
  drop_na(dumpster) |> 
  separate(
    date,
    sep = "-",
    into = c("year_old", "month_old", "day")
  ) |> 
  select(
    -year_old, -month_old
  ) |> 
  mutate(
    homes_powered,
    homes_powered = (weight_tons * 500) / 30,
    trash_wheel = "Mr.",
    year = as.numeric(year)
  ) |> 
  select(
    trash_wheel, month, day, year, everything()
  )
```

Import and clean Professor Trash Wheel and Gwynnda.

``` r
prof_trash_wheel_df =
  read_excel(
    "data/202207 Trash Wheel Collection Data.xlsx",
    sheet = "Professor Trash Wheel",
    range = "A2:M96") |> 
  janitor::clean_names() |> 
  drop_na(dumpster) |> 
  separate(
    date,
    sep = "-",
    into = c("year_old", "month_old", "day")
  ) |> 
  select(
    -year_old, -month_old
  ) |> 
  mutate(
    homes_powered,
    homes_powered = (weight_tons * 500) / 30,
    trash_wheel = "Professor"
  ) |> 
  select(
    trash_wheel, month, day, year, everything()
  )

gwynnda_trash_wheel_df =
  read_excel(
    "data/202207 Trash Wheel Collection Data.xlsx",
    sheet = "Gwynnda Trash Wheel",
    range = "A2:K108") |> 
  janitor::clean_names() |> 
  drop_na(dumpster) |> 
  separate(
    date,
    sep = "-",
    into = c("year_old", "month_old", "day")
  ) |> 
  select(
    -year_old, -month_old
  ) |> 
  mutate(
    homes_powered,
    homes_powered = (weight_tons * 500) / 30,
    trash_wheel = "Gwynnda"
  ) |> 
  select(
    trash_wheel, month, day, year, everything()
  )
```

Combine all 3 trash wheel datasets.

``` r
mr_prof_df =
  full_join(mr_trash_wheel_df, prof_trash_wheel_df)
```

    ## Joining with `by = join_by(trash_wheel, month, day, year, dumpster,
    ## weight_tons, volume_cubic_yards, plastic_bottles, polystyrene, cigarette_butts,
    ## glass_bottles, grocery_bags, chip_bags, homes_powered)`

``` r
trash_wheels_df =
  full_join(mr_prof_df, gwynnda_trash_wheel_df)
```

    ## Joining with `by = join_by(trash_wheel, month, day, year, dumpster,
    ## weight_tons, volume_cubic_yards, plastic_bottles, polystyrene, cigarette_butts,
    ## homes_powered)`

Each of the individual trash wheel datasets (Mr., Professor, and
Gwynnda) contained information about trash collected by these 3 trash
wheels. The data was collected on the dates specified and measured
things such as the weight of trash collected in tons `weight_tons`, an
estimate of the number of homes powered calculated based on the weight
of trash collected `homes_powered`, and the amount of specific trash
items that were collected - i.e., `plastic_bottles` or
`cigarette_butts`. Not all 3 trash wheels measured the exact same
specific trash items. Each row in the dataset is an observation, so
there are 747 observations in the `trash_wheels_df` dataset. The total
weight of trash collected by Professor Trash Wheel was 190.12 tons.
Gwynnda collected 1.63^{4} cigarette butts in July 2021.

## Problem 3

Import, clean, and tidy the dataset of baseline demographics.

``` r
mci_bl_df =
  read_csv("data/MCI_baseline.csv", skip = 1) |> 
  janitor::clean_names() |> 
  mutate(
    age_at_onset = replace(
      age_at_onset, age_at_onset == ".", NA
    ),
    sex = case_match(
      sex,
      1 ~ "male",
      0 ~ "female"
    ),
    apoe4 = case_match(
      apoe4,
      1 ~ "carrier",
      0 ~ "non-carrier"
    )
  ) |> 
  filter(
    is.na(age_at_onset) |
    (as.numeric(age_at_onset) - current_age) > 0
  )
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): Age at onset
    ## dbl (5): ID, Current Age, Sex, Education, apoe4
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Discuss important steps in the import process and relevant features of
the dataset:

To import, I had to include `skip = 1` because the first row in the csv
file included the variable definitions. I used `janitor::clean_names` to
clean the variable names. I used `mutate` to replaces dots that
indicated missing values in `age_at_onset` with NAs. I also used mutate
to make `sex` and `apoe4` non-numeric. To remove participants who did
not meet the inclusion criteria, I used `filter` to keep those who
either never developed MCI (implying that they did not have MCI at
baseline) or those whose onset age was greater than their current age at
baseline. The final tidy `mci_bl_df` dataset is 479 rows by 6 columns.
479 participants were recruited. Of these participants, 93 developed
MCI. The average baseline age is 65.0286013 years.

What proportion of women in the study are APOE4 carriers?

``` r
bl_fem_carrier_df =
  filter(
    mci_bl_df,
    sex == "female",
    apoe4 == "carrier"
  )

bl_fem_non_df =
  filter(
    mci_bl_df,
    sex == "female",
    apoe4 == "non-carrier"
  )
```

42.8571429 percent of women in the study are APOE4 carriers.

Import, clean, and tidy the dataset of longitudinally observed biomarker
values.

``` r
mci_amyloid_df =
  read_csv("data/mci_amyloid.csv", skip = 1) |> 
  janitor::clean_names() |> 
  select(
    id = study_id,
    everything()
  )
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (5): Baseline, Time 2, Time 4, Time 6, Time 8
    ## dbl (1): Study ID
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

I imported the dataset using a similar process as the baseline
demographics one; I needed to include `skip = 1` in the `read_csv`
argument for the same reason. I used `janitor::clean_names` again. Then
I just used select to rename `study_id` to `id` so that it matches the
first dataset. The variable measured was “time (in years) elapsed since
the study baseline to the visit where biomarker amyloid β 42/40 ratio
was measured” for each participant.

Check whether some participants appear in only the baseline or amyloid
datasets:

``` r
range(pull(mci_bl_df, id))
```

    ## [1]   1 483

``` r
range(pull(mci_amyloid_df, id))
```

    ## [1]   1 495

``` r
nrow(mci_bl_df)
```

    ## [1] 479

``` r
nrow(mci_amyloid_df)
```

    ## [1] 487

Because the ranges of the Study IDs included in each dataset are
different, we can tell that there are some participants who appear in
one and not the other. The baseline dataset only goes up to Study ID
483, while the amyloid dataset goes up to Study ID 495, so 12
participants were added after the baseline demographics were recorded.
However, since the amyloid dataset is only 8 participants larger than
the baseline dataset, some of the participants must be in the baseline
set and not amyloid.

Combine the demographic and biomarker datasets so that only participants
who appear in both datasets are retained:

``` r
mci_df =
  inner_join(mci_bl_df, mci_amyloid_df)
```

    ## Joining with `by = join_by(id)`

The resulting dataset contains 471 participants who had their baseline
demographics measured and continued to participate in the study
throughout the follow-up period.

Export the result as a CSV to your data directory:

``` r
write_csv(mci_df, "data/mci.csv")
```
